/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import java.util.Calendar;

/**
 * Programa para calcular idade baseada no ano de nascimento
 * @author luiza
 */
public class CalcularIdade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalcularIdade.class.getName());

    /**
     * Creates new form CalcularIdade
     */
    public CalcularIdade() {
        initComponents();
        configurarSpinner(); // Configura o spinner com valores padrão
    }

    /**
     * Configura o spinner para aceitar apenas anos válidos
     */
    private void configurarSpinner() {
        int anoAtual = Calendar.getInstance().get(Calendar.YEAR);
        // Define um modelo para o spinner: valor mínimo 1900, máximo ano atual, passo 1
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(2000, 1900, anoAtual, 1);
        jSpinnerAnoNascimento.setModel(spinnerModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerAnoNascimento = new javax.swing.JSpinner();
        lblIamgemPerfil = new javax.swing.JLabel();
        lbltextoIdade = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ano de Nascimento:");

        lblIamgemPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/do-utilizador.png"))); // NOI18N

        lbltextoIdade.setText("Idade:");

        lblIdade.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(0, 153, 204));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/calculadora.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblIamgemPerfil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltextoIdade)
                                .addGap(28, 28, 28)
                                .addComponent(lblIdade))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnCalcular)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIamgemPerfil)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltextoIdade)
                    .addComponent(lblIdade))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            // Obtém o ano selecionado no spinner
            int anoNascimento = (Integer) jSpinnerAnoNascimento.getValue();
            
            // Obtém o ano atual
            int anoAtual = Calendar.getInstance().get(Calendar.YEAR);
            
            // Calcula a idade
            int idade = anoAtual - anoNascimento;
            
            // Valida se a idade é positiva
            if (idade < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Ano de nascimento não pode ser maior que o ano atual!", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Exibe a idade calculada
            lblIdade.setText(String.valueOf(idade + " anos."));
            
        } catch (Exception e) {
            // Trata possíveis exceções
            logger.severe("Erro ao calcular idade: " + e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Erro ao calcular idade. Verifique o valor informado.", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalcularIdade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinnerAnoNascimento;
    private javax.swing.JLabel lblIamgemPerfil;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lbltextoIdade;
    // End of variables declaration//GEN-END:variables
}
