/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author luiza
 */

public class SistemaPagamentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaPagamentos.class.getName());
    private Pagamento pagamentoSelecionado;
    private String tipoPagamento;
    private Timer timer;
    
    public SistemaPagamentos() {
        initComponents();
        iniciarRelogio();
    }
    
    private void iniciarRelogio() {
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                atualizarHorario();
            }
        }, 0, 60000);
        atualizarHorario(); // Atualiza o horario
    }
    
    private void atualizarHorario() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        String horarioAtual = LocalDateTime.now().format(formatter);
        
        // Atualiza a interface na thread EDT
        java.awt.EventQueue.invokeLater(() -> {
            lblHorario.setText(horarioAtual);
        });
    }
    
    private void selecionarPagamento(String tipo, Pagamento pagamento) {
        this.tipoPagamento = tipo;
        this.pagamentoSelecionado = pagamento;
        
        // Feedback visual para o usuário
        JOptionPane.showMessageDialog(this, 
            tipo + " selecionado!", 
            "Forma de Pagamento", 
            JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHorario = new javax.swing.JLabel();
        imgBateria = new javax.swing.JLabel();
        imgWifi = new javax.swing.JLabel();
        imgSinal = new javax.swing.JLabel();
        imgSeta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDinheiro = new javax.swing.JButton();
        btnPix = new javax.swing.JButton();
        btnCartao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 43, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHorario.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblHorario.setText("12:30");

        imgBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/telefone.png"))); // NOI18N

        imgWifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/bateria-cheia.png"))); // NOI18N

        imgSinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/sinal-wifi.png"))); // NOI18N

        imgSeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/seta-esquerda (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Forma de Pagamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgSeta)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgWifi)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(imgWifi)
                    .addComponent(imgSinal)
                    .addComponent(imgBateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgSeta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/money.png"))); // NOI18N
        btnDinheiro.setText("              Dinheiro");
        btnDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDinheiroActionPerformed(evt);
            }
        });

        btnPix.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/pix.png"))); // NOI18N
        btnPix.setText("              Pix");
        btnPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPixActionPerformed(evt);
            }
        });

        btnCartao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/credit-card.png"))); // NOI18N
        btnCartao.setText("            Cartão");
        btnCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(btnPix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCartao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 350, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnConfirmar.setBackground(new java.awt.Color(251, 86, 112));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixActionPerformed
        selecionarPagamento("PIX", new PagamentoPix());
    }//GEN-LAST:event_btnPixActionPerformed

    private void btnCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaoActionPerformed
        selecionarPagamento("Cartão", new PagamentoCartao());
    }//GEN-LAST:event_btnCartaoActionPerformed

    private void btnDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinheiroActionPerformed
        selecionarPagamento("Dinheiro", new PagamentoDinheiro());
    }//GEN-LAST:event_btnDinheiroActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (pagamentoSelecionado == null) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecione uma forma de pagamento!", 
                "Atenção", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Solicitar valor da compra
        String valorStr = JOptionPane.showInputDialog(this, 
            "Digite o valor da compra:", 
            "Valor da Compra", 
            JOptionPane.QUESTION_MESSAGE);
        
        if (valorStr == null || valorStr.trim().isEmpty()) {
            return; // Usuário cancelou
        }
        
        try {
            double valor = Double.parseDouble(valorStr.replace(",", "."));
            
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "Valor deve ser maior que zero!", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Calcular total
            double valorFinal = pagamentoSelecionado.calcularTotal(valor);
            
            // Gerar e mostrar recibo
            String recibo = pagamentoSelecionado.imprimirRecibo(valor);
            
            DecimalFormat df = new DecimalFormat("#,##0.00");
            String mensagemFinal = recibo + "\n\n" +
                "Forma de pagamento: " + tipoPagamento + "\n" +
                "Valor a pagar: R$ " + df.format(valorFinal);
            
            JOptionPane.showMessageDialog(this, 
                mensagemFinal, 
                "Recibo de Pagamento", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Limpar seleção para próxima compra
            pagamentoSelecionado = null;
            tipoPagamento = null;
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Valor inválido! Digite um número válido.", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SistemaPagamentos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCartao;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDinheiro;
    private javax.swing.JButton btnPix;
    private javax.swing.JLabel imgBateria;
    private javax.swing.JLabel imgSeta;
    private javax.swing.JLabel imgSinal;
    private javax.swing.JLabel imgWifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblHorario;
    // End of variables declaration//GEN-END:variables
}
