/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba;
import javax.swing.JOptionPane;
/**
 *
 * @author luiza
 * Classe principal da interface gráfica para cálculo de formas geométricas.
 * Implementa a hierarquia de classes e fornece interface para usuário.
 */

public class FormasView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormasView.class.getName());

    /**
     * Creates new form FormasView
     */
    public FormasView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormas = new javax.swing.JLabel();
        imgFormas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnQuadrado = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCubo = new javax.swing.JButton();
        btnEsfera = new javax.swing.JButton();
        btnPiramide = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 97, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFormas.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblFormas.setText("Formas Geométricas");

        imgFormas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/formas (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(imgFormas)
                .addGap(18, 18, 18)
                .addComponent(lblFormas)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imgFormas)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnQuadrado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnQuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/square.png"))); // NOI18N
        btnQuadrado.setText("              Quadrado");
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });

        btnCirculo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/circle.png"))); // NOI18N
        btnCirculo.setText("                Círculo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnTriangulo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/triangle.png"))); // NOI18N
        btnTriangulo.setText("                 Triângulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuadrado)
                .addGap(18, 18, 18)
                .addComponent(btnCirculo)
                .addGap(18, 18, 18)
                .addComponent(btnTriangulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCubo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/cube.png"))); // NOI18N
        btnCubo.setText("                   Cubo");
        btnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboActionPerformed(evt);
            }
        });

        btnEsfera.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnEsfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/sphere.png"))); // NOI18N
        btnEsfera.setText("                    Esfera");
        btnEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsferaActionPerformed(evt);
            }
        });

        btnPiramide.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPiramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/prism.png"))); // NOI18N
        btnPiramide.setText("                 Pirâmide");
        btnPiramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiramideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEsfera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCubo)
                .addGap(18, 18, 18)
                .addComponent(btnEsfera)
                .addGap(18, 18, 18)
                .addComponent(btnPiramide)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsferaActionPerformed
        try {
            double raio = obterNumeroValido("Digite o raio da esfera:");
            Esfera esfera = new Esfera(raio);
            
            String resultado = String.format(
                "ESFERA\n" +
                "Raio: %.2f\n" +
                "Área Superficial: %.2f\n" +
                "Volume: %.2f",
                raio, esfera.obterArea(), esfera.obterVolume()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Esfera", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular esfera: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEsferaActionPerformed

    private void btnPiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiramideActionPerformed
        try {
            double base = obterNumeroValido("Digite a medida da base da pirâmide:");
            double altura = obterNumeroValido("Digite a altura da pirâmide:");
            Piramide piramide = new Piramide(base, altura);
            
            String resultado = String.format(
                "PIRÂMIDE\n" +
                "Base: %.2f\n" +
                "Altura: %.2f\n" +
                "Área Superficial: %.2f\n" +
                "Volume: %.2f",
                base, altura, piramide.obterArea(), piramide.obterVolume()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Pirâmide", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular pirâmide: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnPiramideActionPerformed

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
        try {
            double lado = obterNumeroValido("Digite o lado do quadrado:");
            Quadrado quadrado = new Quadrado(lado);
            
            String resultado = String.format(
                "QUADRADO\n" +
                "Lado: %.2f\n" +
                "Área: %.2f",
                lado, quadrado.obterArea()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Quadrado", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular quadrado: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnQuadradoActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        try {
            double raio = obterNumeroValido("Digite o raio do círculo:");
            Circulo circulo = new Circulo(raio);
            
            String resultado = String.format(
                "CÍRCULO\n" +
                "Raio: %.2f\n" +
                "Área: %.2f",
                raio, circulo.obterArea()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Círculo", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular círculo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        try {
            double base = obterNumeroValido("Digite a base do triângulo:");
            double altura = obterNumeroValido("Digite a altura do triângulo:");
            Triangulo triangulo = new Triangulo(base, altura);
            
            String resultado = String.format(
                "TRIÂNGULO\n" +
                "Base: %.2f\n" +
                "Altura: %.2f\n" +
                "Área: %.2f",
                base, altura, triangulo.obterArea()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Triângulo", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular triângulo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboActionPerformed
        try {
            double aresta = obterNumeroValido("Digite a aresta do cubo:");
            Cubo cubo = new Cubo(aresta);
            
            String resultado = String.format(
                "CUBO\n" +
                "Aresta: %.2f\n" +
                "Área Superficial: %.2f\n" +
                "Volume: %.2f",
                aresta, cubo.obterArea(), cubo.obterVolume()
            );
            
            JOptionPane.showMessageDialog(this, resultado, "Resultado - Cubo", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            if (!e.getMessage().equals("Operação cancelada pelo usuário")) {
                exibirErro("Erro ao calcular cubo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCuboActionPerformed
    
    /**
     * Método para exibir mensagens de erro de forma padronizada.
     * @param mensagem Mensagem de erro a ser exibida.
     */
    private void exibirErro(String mensagem) {
        JOptionPane.showMessageDialog(this, 
            mensagem, 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * Método para validar se uma string pode ser convertida para número positivo.
     * @param texto Texto a ser validado.
     * @return true se for válido, false caso contrário.
     */
    private boolean validarNumeroPositivo(String texto) {
        try {
            double valor = Double.parseDouble(texto);
            return valor > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    /**
     * Método para obter um número válido do usuário.
     * @param mensagem Mensagem a ser exibida.
     * @return Número válido digitado pelo usuário.
     */
    private double obterNumeroValido(String mensagem) {
        while (true) {
            String input = JOptionPane.showInputDialog(this, mensagem);
            if (input == null) {
                throw new RuntimeException("Operação cancelada pelo usuário");
            }
            if (validarNumeroPositivo(input)) {
                return Double.parseDouble(input);
            } else {
                exibirErro("Por favor, digite um número positivo válido.");
            }
        }
    }
    /**
     * Método principal que demonstra o uso do array de formas.
     * Cria um array com diferentes formas e exibe suas informações.
     */
    public void demonstrarHierarquia() {
        // Criando array de formas (polimorfismo)
        Forma[] formas = new Forma[6];
        
        formas[0] = new Quadrado(5);
        formas[1] = new Circulo(3);
        formas[2] = new Triangulo(4, 6);
        formas[3] = new Cubo(4);
        formas[4] = new Esfera(3);
        formas[5] = new Piramide(4, 6);
        
        StringBuilder resultado = new StringBuilder();
        resultado.append("DEMONSTRAÇÃO DA HIERARQUIA DE FORMAS\n\n");
        
        // Processando cada forma no array
        for (Forma forma : formas) {
            resultado.append(forma.toString()).append("\n");
            resultado.append("Tipo: ").append(forma.getTipo()).append("\n");
            
            if (forma instanceof Formas2D) {
                Formas2D forma2D = (Formas2D) forma;
                resultado.append(String.format("Área: %.2f", forma2D.obterArea()));
            } else if (forma instanceof Formas3D) {
                Formas3D forma3D = (Formas3D) forma;
                resultado.append(String.format("Área Superficial: %.2f\n", forma3D.obterArea()));
                resultado.append(String.format("Volume: %.2f", forma3D.obterVolume()));
            }
            
            resultado.append("\n").append("-".repeat(50)).append("\n");
        }
        
        JOptionPane.showMessageDialog(this, resultado.toString(), 
            "Demonstração da Hierarquia", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            FormasView view = new FormasView();
            view.setVisible(true);
            // Demonstra a hierarquia ao iniciar o programa
            view.demonstrarHierarquia();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCubo;
    private javax.swing.JButton btnEsfera;
    private javax.swing.JButton btnPiramide;
    private javax.swing.JButton btnQuadrado;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel imgFormas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblFormas;
    // End of variables declaration//GEN-END:variables
}
