/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author luiza
 */
public class JogoGenio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JogoGenio.class.getName());
    private int numeroPensado; // Armazena o número que o gênio está pensando

    /**
     * Creates new form JogoGenio
     */
    public JogoGenio() {
        initComponents();
        inicializarJogo(); // Configura o jogo após inicializar componentes
    }

    /**
     * Inicializa as configurações do jogo
     */
    private void inicializarJogo() {
        // Configura spinner para valores entre 1 e 5
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, 5, 1);
        spValores.setModel(spinnerModel);
        
        // Gera número aleatório entre 1 e 5
        numeroPensado = (int) (Math.random() * 5) + 1;
        
        // Configura mensagem inicial com formatação para caber no balão
        configurarLabelFala();
        lblFala.setText("<html><div style='text-align: center;'>Vou pensar em um valor<br>entre 1 e 5<br>tente advinhar!</div></html>");
        
        // Adiciona ação ao botão Palpite
        btnPalpite.addActionListener(e -> verificarPalpite());
    }
    /**
    * Configura a label
    */
    private void configurarLabelFala() {
    lblFala.setText("<html><div style='text-align: center;'>Vou pensar em um valor<br>entre 1 e 5<br>tente advinhar!</div></html>");
    }

    /**
    * Verifica se o palpite do usuário está correto
     */
    private void verificarPalpite() {
        int palpite = (Integer) spValores.getValue(); // Obtém valor do spinner
    
        // centraliza as mensagens
        if (palpite == numeroPensado) {
        lblFala.setText("<html><div style='text-align: center;'>Acertou!</div></html>");
        } else {
        lblFala.setText("<html><div style='text-align: center;'>Errou! Eu pensei<br>no valor " + numeroPensado + "</div></html>");
        }
    
        // Gera novo número para próxima rodada
        numeroPensado = (int) (Math.random() * 5) + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFala = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        spValores = new javax.swing.JSpinner();
        lblValor = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 48, -1, -1));

        lblFala.setFont(new java.awt.Font("Pristina", 1, 20)); // NOI18N
        lblFala.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 90));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/images/genioAkinator.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));
        getContentPane().add(spValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        lblValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValor.setText("Valor:");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnPalpite.setText("Palpite!");
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JogoGenio jogo = new JogoGenio();
            jogo.setVisible(true);
            jogo.setLocationRelativeTo(null); // Centraliza a janela
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFala;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spValores;
    // End of variables declaration//GEN-END:variables
}
